# SPDX-FileCopyrightText: 2024 Eric Dejouhanet <eric.dejouhanet@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

Dependencies:
- 'on': ['Linux/Qt5, Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/breeze-icons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kinit': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/knotifyconfig': '@latest-kf6'
    'frameworks/kplotting': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'

- 'on': ['Linux/Qt5, Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/breeze-icons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/kinit': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/kplotting': '@stable'

#- 'on': ['Android']
#  'require':

Options:
  in-source-build: False
  setup-dbus-session: True
  setup-x-environment: True
