# SPDX-FileCopyrightText: 2024 Eric Dejouhanet <eric.dejouhanet@gmail.com>
# SPDX-License-Identifier: GPL-2.0-or-later

Dependencies:

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6', 'macOS/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/kconfig': '@stable-kf6'
    'frameworks/kguiaddons': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kplotting': '@stable-kf6'
    'libs/stellarsolver': '@stable-kf6'

- 'on': ['Linux/Qt6','Windows/Qt6']
  'require':
    'frameworks/breeze-icons': '@stable-kf6'
    'frameworks/kcrash': '@stable-kf6'
    'frameworks/kdoctools': '@stable-kf6'
    'frameworks/knewstuff': '@stable-kf6'
    'frameworks/knotifications': '@stable-kf6'
    'frameworks/knotifyconfig': '@stable-kf6'
    'frameworks/kxmlgui': '@stable-kf6'

#- 'on': ['Android']
#  'require':

Environment:
  CMAKE_VERBOSE_MAKEFILE: "ON"

Options:
  in-source-build: False
  setup-dbus-session: True
  setup-x-environment: True
  cmake-options: '--trace'
  use-ccache: True
